### ISSUE TITLE
Binary switches get locked by logic processors

### ISSUE THREAD

**Issue by SMOLKEYS** [Goobrr/Esoterum-Solutions#16]
**Version:**
v1.1.1 (Workflow Release #57)

**Issue:**
Binary switches get locked to an `on` state when being told to turn off by processors

**Steps to replicate:**
1. Link a binary switch to the processor
2. `control enabled switch1 0 0 0 0` (Paste in processor)

**Save file:**
[Here](https://github.com/SMOLKEYS/BuggedSaveFiles/blob/master/brokenesosave.msav?raw=true)

**Crash log:**
None

**Comment by Goobrr** [comment]
might be fixed
